package app.execution.tests.inventory;

import app.execution.configs.configINV;
import org.openqa.selenium.By;
import org.testng.annotations.Test;

import java.io.IOException;

public class CreateInventoryTest implements configINV {

    public String newPiece = "Cabinet";
//create the transaction with type Pickup
    @Test
    public void createNewInventory() throws InterruptedException, IOException {

        appInv.getBasicMethods().clickOnTheCreateNewInventoryButton();
        appInv.getBasicMethods().type(By.id("inventory_name"),"Alisa2");
        appInv.getBasicMethods().type(By.id("inventory_id"), "10947-1-1");
        appInv.getBasicMethods().hideKeyboard();
        appInv.getBasicMethods().clickOnTheCreateButton();
        appInv.getBasicMethods().click_CubeSheet_button_onTheInventoriesScreen();
        appInv.getBasicMethods().clickOnTheAddPieceButton();
        appInv.getBasicMethods().selectLocationForTheNewPiece();
        appInv.getBasicMethods().selectPackageForNewPiece();
        appInv.getBasicMethods().selectPBOForNewPiece();
        appInv.getBasicMethods().swipeScreenDown();
        appInv.getBasicMethods().addItemIntoNewPiece3(newPiece);
        appInv.getBasicMethods().click_Item_OnPackageScreen_toOpenItemDetailsScreen();
        appInv.getBasicMethods().changeTypeOfNewItem();
        appInv.getBasicMethods().addConditionToTheNewItem();
        appInv.getBasicMethods().hideKeyboard();
        appInv.getBasicMethods().addCommentToTheNewItem();
        appInv.getBasicMethods().hideKeyboard();
        appInv.getBasicMethods().addCondition();
        appInv.getBasicMethods().addLocation();
        appInv.getBasicMethods().hideKeyboard();
        appInv.getBasicMethods().attachPhotoFromGallery();
        appInv.getBasicMethods().attachPhotoFromCamera();
        appInv.getBasicMethods().clickOnSavePhotoFromCamera();
        appInv.getBasicMethods().clickToTheReturnUpButton();
        appInv.getBasicMethods().clickToTheReturnUpButton();
        appInv.getBasicMethods().clickToTheReturnUpButton();
        appInv.getBasicMethods().swipeScreenToTheLeft();
        appInv.getBasicMethods().select_Room_withItem_inRoomsGrid_onRoomsScreen();
        appInv.getBasicMethods().click_InspectionInfo_button();
        appInv.getBasicMethods().fillDescriptionField();
        appInv.getBasicMethods().hideKeyboard();
        appInv.getBasicMethods().fillConditionField();
        appInv.getBasicMethods().hideKeyboard();
        appInv.getBasicMethods().attachPhotoFromGallery();
        appInv.getBasicMethods().attachPhotoConditions();
        appInv.getBasicMethods().clickOnSavePhotoFromCamera();
        appInv.getBasicMethods().selectPropertyBeforePacking();
        appInv.getBasicMethods().clickOnTheSelectConditionButtonOfPropertyBeforePacking();
        appInv.getBasicMethods().clickOnPropertyConditionsFieldAfterPacking();
        appInv.getBasicMethods().attachPhotoFromGallery();
        appInv.getBasicMethods().attachPhotoConditions();
        appInv.getBasicMethods().clickOnSavePhotoFromCamera();
        appInv.getBasicMethods().selectPropertyAfterPacking();
        appInv.getBasicMethods().clickOnTheSelectConditionButtonOfPropertyAfterPacking();
        appInv.getBasicMethods().clickToTheReturnUpButton();
        appInv.getBasicMethods().clickToTheReturnUpButton();
        appInv.getBasicMethods().swipeScreenToTheLeft();
        appInv.getBasicMethods().clickToAddSkidButton();
        appInv.getBasicMethods().swipeScreenDown();
        appInv.getBasicMethods().clickToTheSkidContentButton();
        appInv.getBasicMethods().clickToTheLoadSkidButton();
        appInv.getBasicMethods().clickToTheReturnUpButton();
        appInv.getBasicMethods().attachPhotoFromGallery();
        appInv.getBasicMethods().attachPhotoToTheNewSkid();
        appInv.getBasicMethods().clickOnSavePhotoFromCamera();
        appInv.getBasicMethods().clickToTheSkidOKButton();
        Thread.sleep(2000);
        appInv.getBasicMethods().click_NavigateMenu_button();
        appInv.getBasicMethods().clickOnTheSummaries();
        appInv.getBasicMethods().click_Packers_button_onNavigateMenu();
        appInv.getBasicMethods().clickToTheReturnUpButton();
        appInv.getBasicMethods().click_NavigateMenu_button();
        appInv.getBasicMethods().click_CartonsSummary_onNavigateMenu();
        appInv.getBasicMethods().clickToTheReturnUpButton();
        appInv.getBasicMethods().click_NavigateMenu_button();
        appInv.getBasicMethods().click_Appliances_onNavigateMenu();
        appInv.getBasicMethods().clickToTheReturnUpButton();
        appInv.getBasicMethods().click_NavigateMenu_button();
        appInv.getBasicMethods().swipeScreenDownMenu();
        appInv.getBasicMethods().click_AdditionalServices_button_onNavigateMenu();
        appInv.getBasicMethods().click_AdditionalMaterials_button_onNavigateMenu();
        appInv.getBasicMethods().clickToTheReturnUpButton();
        appInv.getBasicMethods().click_NavigateMenu_button();
        appInv.getBasicMethods().click_Services_button_onNavigateMenu();
        appInv.getBasicMethods().openServiceList();
        appInv.getBasicMethods().addServiceText();
        appInv.getBasicMethods().clickOnTheOKButton();
        appInv.getBasicMethods().addValueFromList();
        appInv.getBasicMethods().attachPhotoFromCameraToService();
        appInv.getBasicMethods().clickOnSavePhotoFromCamera();
        appInv.getBasicMethods().createSingnatureforAditionalService();
        appInv.getBasicMethods().clickToTheReturnUpButton();
        appInv.getBasicMethods().clickToTheReturnUpButton();
        appInv.getBasicMethods().click_NavigateMenu_button();
        appInv.getBasicMethods().click_AdditionalInfo__button_onNavigateMenu();
        appInv.getBasicMethods().openFirstPropertiesList();
        appInv.getBasicMethods().createSingnatureforAditionalService();
        appInv.getBasicMethods().clickToTheReturnUpButton();
        appInv.getBasicMethods().addQuestionText();
        appInv.getBasicMethods().clickOnTheOKButton();
        appInv.getBasicMethods().clickToTheReturnUpButton();
        appInv.getBasicMethods().click_NavigateMenu_button();
        appInv.getBasicMethods().swipeScreenDownMenu();
        appInv.getBasicMethods().click_Documents_button_onNavigateMenu();
        appInv.getBasicMethods().clickOnTheAddDocumentButton();
        appInv.getBasicMethods().fillDocumentNameField();
        appInv.getBasicMethods().hideKeyboard();
        appInv.getBasicMethods().attachPhotoToTheDocumentSectionFromGallery();
        Thread.sleep(2000);
        appInv.getBasicMethods().clickOnTheAddDocumentButton();
        appInv.getBasicMethods().fillDocumentNameField();
        appInv.getBasicMethods().hideKeyboard();
        appInv.getBasicMethods().attachPhotoToTheDocumentSection();
        appInv.getBasicMethods().clickOnSavePhotoFromCamera();
        appInv.getBasicMethods().clickOnTheDeviceReturnButton();
        appInv.getBasicMethods().click_NavigateMenu_button();
        appInv.getBasicMethods().swipeScreenDownMenu();
        appInv.getBasicMethods().clickToTheSignAndSendButton();
        appInv.getBasicMethods().swipeScreenDown();
        appInv.getBasicMethods().clickOnTheClientShipperButton();
        appInv.getBasicMethods().createSingnature2();
        appInv.getBasicMethods().clickToTheReturnUpButton();
        appInv.getBasicMethods().clickOnTheForemanDriverButton();
        appInv.getBasicMethods().createSingnature2();
        appInv.getBasicMethods().clickToTheReturnUpButton();
        appInv.getBasicMethods().swipeScreenUp();
        appInv.getBasicMethods().clickOnTheUploadButton();
        appInv.getBasicMethods().clickOnTheOKButtonOnThePopUp();
        appInv.getBasicMethods().screenshot();
        appInv.getBasicMethods().clickToTheReturnUpButton();
    }
}
